package by.jwd.task6.controller.command;

public enum CommandName {
    
    SIGN_IN, SIGN_UP, LOCALIZATION, TO_MAIN_PAGE, TO_ERROR_PAGE, SIGN_OUT, GO_TO_TEST_PAGE, CHECK_EMAIL_AVAILABILITY,
    CONTACT_US, REGISTER_HOTEL, REGISTER_ROOMS, REGISTER_MEALS, SEARCH_HOTELS_BY_INPUT;

}
